GET http://localhost:3003/ping
###

GET http://localhost:3003/videos
###

POST http://localhost:3003/videos
Content-Type: application/json

{
    "id": "v004",
    "title": "LLMs",
    "time_segunds": 1500
}
###

PUT  http://localhost:3003/videos/v004
Content-Type: application/json

{
    "title": "Teste de IA"
}
###

DELETE http://localhost:3003/videos/v004
###